export const mockProvinces = [
  { _id: 'p1', name: 'Hà Nội', region_id: 'r1' },
  { _id: 'p2', name: 'Đà Nẵng', region_id: 'r2' },
  { _id: 'p3', name: 'Hồ Chí Minh', region_id: 'r3' },
  { _id: 'p4', name: 'Nha Trang', region_id: 'r2' },
  { _id: 'p5', name: 'Phú Quốc', region_id: 'r3' },
  { _id: 'p6', name: 'Hạ Long', region_id: 'r1' },
];

export const mockRegions = [
  { _id: 'r1', name: 'Miền Bắc' },
  { _id: 'r2', name: 'Miền Trung' },
  { _id: 'r3', name: 'Miền Nam' },
];

export const mockTours = [
  {
    _id: 't1',
    tour_code: 'HN-HL-01',
    name: 'Hà Nội - Hạ Long 3 ngày 2 đêm',
    description: 'Tour du lịch Hà Nội - Hạ Long với nhiều điểm tham quan hấp dẫn',
    images: ['/placeholder.png?height=200&width=300'],
    services: ['Ăn uống', 'Vé tham quan', 'Hướng dẫn viên'],
    itinerary: [
      { day: 1, title: 'Khởi hành từ Hà Nội', description: 'Khởi hành từ Hà Nội đi Hạ Long' },
      { day: 2, title: 'Tham quan Vịnh Hạ Long', description: 'Tham quan các điểm du lịch nổi tiếng tại Vịnh Hạ Long' },
      { day: 3, title: 'Trở về Hà Nội', description: 'Kết thúc chuyến đi và trở về Hà Nội' },
    ],
    policies: [
      { title: 'Chính sách hủy tour', description: 'Hủy tour trước 3 ngày được hoàn 50% tiền cọc' },
      { title: 'Chính sách trẻ em', description: 'Trẻ em dưới 5 tuổi miễn phí, từ 5-10 tuổi tính 50% giá người lớn' },
    ],
    duration: '3N2Đ',
    starting_province_id: 'p1',
    destination_province_id: 'p6',
    transportation: 'Xe buýt',
    representative_price: {
      adult: 3500000,
      new_price: 3200000,
    },
    departure_summary: [
      { departure_id: 'd1', departure_date: '2025-06-25' },
      { departure_id: 'd2', departure_date: '2025-07-15' },
    ],
    total_slots_booked: 10,
    is_bestseller: true,
    is_active: true,
  },
  {
    _id: 't2',
    tour_code: 'HN-DN-01',
    name: 'Hà Nội - Đà Nẵng 4 ngày 3 đêm',
    description: 'Tour du lịch Hà Nội - Đà Nẵng với nhiều điểm tham quan hấp dẫn',
    images: ['/placeholder.svg?height=200&width=300'],
    services: ['Ăn uống', 'Vé tham quan', 'Hướng dẫn viên', 'Vé máy bay'],
    itinerary: [
      { day: 1, title: 'Khởi hành từ Hà Nội', description: 'Khởi hành từ Hà Nội đi Đà Nẵng bằng máy bay' },
      { day: 2, title: 'Thăm quan Bà Nà Hills', description: 'Tham quan Bà Nà Hills và Cầu Vàng' },
      { day: 3, title: 'Thăm quan Hội An', description: 'Thăm quan phố cổ Hội An' },
      { day: 4, title: 'Trở về Hà Nội', description: 'Kết thúc chuyến đi và trở về Hà Nội' },
    ],
    policies: [
      { title: 'Chính sách hủy tour', description: 'Hủy tour trước 7 ngày được hoàn 50% tiền cọc' },
      { title: 'Chính sách trẻ em', description: 'Trẻ em dưới 2 tuổi miễn phí, từ 2-10 tuổi tính 75% giá người lớn' },
    ],
    duration: '4N3Đ',
    starting_province_id: 'p1',
    destination_province_id: 'p2',
    transportation: 'Máy bay',
    representative_price: {
      adult: 7500000,
      new_price: 6800000,
    },
    departure_summary: [
      { departure_id: 'd3', departure_date: '2025-07-01' },
      { departure_id: 'd4', departure_date: '2025-07-25' },
    ],
    total_slots_booked: 2,
    is_bestseller: true,
    is_active: false,
  },
  {
    _id: 't3',
    tour_code: 'HN-DN-01',
    name: 'Hà Nội - Đà Nẵng 4 ngày 3 đêm',
    description: 'Tour du lịch Hà Nội - Đà Nẵng với nhiều điểm tham quan hấp dẫn',
    images: ['/placeholder.svg?height=200&width=300'],
    services: ['Ăn uống', 'Vé tham quan', 'Hướng dẫn viên', 'Vé máy bay'],
    itinerary: [
      { day: 1, title: 'Khởi hành từ Hà Nội', description: 'Khởi hành từ Hà Nội đi Đà Nẵng bằng máy bay' },
      { day: 2, title: 'Thăm quan Bà Nà Hills', description: 'Tham quan Bà Nà Hills và Cầu Vàng' },
      { day: 3, title: 'Thăm quan Hội An', description: 'Thăm quan phố cổ Hội An' },
      { day: 4, title: 'Trở về Hà Nội', description: 'Kết thúc chuyến đi và trở về Hà Nội' },
    ],
    policies: [
      { title: 'Chính sách hủy tour', description: 'Hủy tour trước 7 ngày được hoàn 50% tiền cọc' },
      { title: 'Chính sách trẻ em', description: 'Trẻ em dưới 2 tuổi miễn phí, từ 2-10 tuổi tính 75% giá người lớn' },
    ],
    duration: '4N3Đ',
    starting_province_id: 'p1',
    destination_province_id: 'p2',
    transportation: 'Máy bay',
    representative_price: {
      adult: 7500000,
      new_price: 6800000,
    },
    departure_summary: [
      { departure_id: 'd3', departure_date: '2025-07-01' },
      { departure_id: 'd4', departure_date: '2025-07-25' },
    ],
    total_slots_booked: 2,
    is_bestseller: true,
    is_active: false,
  },
  {
    _id: 't4',
    tour_code: 'HN-DN-01',
    name: 'Hà Nội - Đà Nẵng 4 ngày 3 đêm',
    description: 'Tour du lịch Hà Nội - Đà Nẵng với nhiều điểm tham quan hấp dẫn',
    images: ['/placeholder.svg?height=200&width=300'],
    services: ['Ăn uống', 'Vé tham quan', 'Hướng dẫn viên', 'Vé máy bay'],
    itinerary: [
      { day: 1, title: 'Khởi hành từ Hà Nội', description: 'Khởi hành từ Hà Nội đi Đà Nẵng bằng máy bay' },
      { day: 2, title: 'Thăm quan Bà Nà Hills', description: 'Tham quan Bà Nà Hills và Cầu Vàng' },
      { day: 3, title: 'Thăm quan Hội An', description: 'Thăm quan phố cổ Hội An' },
      { day: 4, title: 'Trở về Hà Nội', description: 'Kết thúc chuyến đi và trở về Hà Nội' },
    ],
    policies: [
      { title: 'Chính sách hủy tour', description: 'Hủy tour trước 7 ngày được hoàn 50% tiền cọc' },
      { title: 'Chính sách trẻ em', description: 'Trẻ em dưới 2 tuổi miễn phí, từ 2-10 tuổi tính 75% giá người lớn' },
    ],
    duration: '4N3Đ',
    starting_province_id: 'p1',
    destination_province_id: 'p2',
    transportation: 'Máy bay',
    representative_price: {
      adult: 7500000,
      new_price: 6800000,
    },
    departure_summary: [
      { departure_id: 'd3', departure_date: '2025-07-01' },
      { departure_id: 'd4', departure_date: '2025-07-25' },
    ],
    total_slots_booked: 2,
    is_bestseller: true,
    is_active: false,
  },
  {
    _id: 't5',
    tour_code: 'HN-DN-01',
    name: 'Hà Nội - Đà Nẵng 4 ngày 3 đêm',
    description: 'Tour du lịch Hà Nội - Đà Nẵng với nhiều điểm tham quan hấp dẫn',
    images: ['/placeholder.svg?height=200&width=300'],
    services: ['Ăn uống', 'Vé tham quan', 'Hướng dẫn viên', 'Vé máy bay'],
    itinerary: [
      { day: 1, title: 'Khởi hành từ Hà Nội', description: 'Khởi hành từ Hà Nội đi Đà Nẵng bằng máy bay' },
      { day: 2, title: 'Thăm quan Bà Nà Hills', description: 'Tham quan Bà Nà Hills và Cầu Vàng' },
      { day: 3, title: 'Thăm quan Hội An', description: 'Thăm quan phố cổ Hội An' },
      { day: 4, title: 'Trở về Hà Nội', description: 'Kết thúc chuyến đi và trở về Hà Nội' },
    ],
    policies: [
      { title: 'Chính sách hủy tour', description: 'Hủy tour trước 7 ngày được hoàn 50% tiền cọc' },
      { title: 'Chính sách trẻ em', description: 'Trẻ em dưới 2 tuổi miễn phí, từ 2-10 tuổi tính 75% giá người lớn' },
    ],
    duration: '4N3Đ',
    starting_province_id: 'p1',
    destination_province_id: 'p2',
    transportation: 'Máy bay',
    representative_price: {
      adult: 7500000,
      new_price: 6800000,
    },
    departure_summary: [
      { departure_id: 'd3', departure_date: '2025-07-01' },
      { departure_id: 'd4', departure_date: '2025-07-25' },
    ],
    total_slots_booked: 2,
    is_bestseller: true,
    is_active: false,
  },
  {
    _id: 't6',
    tour_code: 'HN-DN-01',
    name: 'Hà Nội - Đà Nẵng 4 ngày 3 đêm',
    description: 'Tour du lịch Hà Nội - Đà Nẵng với nhiều điểm tham quan hấp dẫn',
    images: ['/placeholder.svg?height=200&width=300'],
    services: ['Ăn uống', 'Vé tham quan', 'Hướng dẫn viên', 'Vé máy bay'],
    itinerary: [
      { day: 1, title: 'Khởi hành từ Hà Nội', description: 'Khởi hành từ Hà Nội đi Đà Nẵng bằng máy bay' },
      { day: 2, title: 'Thăm quan Bà Nà Hills', description: 'Tham quan Bà Nà Hills và Cầu Vàng' },
      { day: 3, title: 'Thăm quan Hội An', description: 'Thăm quan phố cổ Hội An' },
      { day: 4, title: 'Trở về Hà Nội', description: 'Kết thúc chuyến đi và trở về Hà Nội' },
    ],
    policies: [
      { title: 'Chính sách hủy tour', description: 'Hủy tour trước 7 ngày được hoàn 50% tiền cọc' },
      { title: 'Chính sách trẻ em', description: 'Trẻ em dưới 2 tuổi miễn phí, từ 2-10 tuổi tính 75% giá người lớn' },
    ],
    duration: '4N3Đ',
    starting_province_id: 'p1',
    destination_province_id: 'p2',
    transportation: 'Máy bay',
    representative_price: {
      adult: 7500000,
      new_price: 6800000,
    },
    departure_summary: [
      { departure_id: 'd3', departure_date: '2025-07-01' },
      { departure_id: 'd4', departure_date: '2025-07-25' },
    ],
    total_slots_booked: 2,
    is_bestseller: false,
    is_active: false,
  },
  {
    _id: 't7',
    tour_code: 'HN-DN-01',
    name: 'Hà Nội - Đà Nẵng 4 ngày 3 đêm',
    description: 'Tour du lịch Hà Nội - Đà Nẵng với nhiều điểm tham quan hấp dẫn',
    images: ['/placeholder.svg?height=200&width=300'],
    services: ['Ăn uống', 'Vé tham quan', 'Hướng dẫn viên', 'Vé máy bay'],
    itinerary: [
      { day: 1, title: 'Khởi hành từ Hà Nội', description: 'Khởi hành từ Hà Nội đi Đà Nẵng bằng máy bay' },
      { day: 2, title: 'Thăm quan Bà Nà Hills', description: 'Tham quan Bà Nà Hills và Cầu Vàng' },
      { day: 3, title: 'Thăm quan Hội An', description: 'Thăm quan phố cổ Hội An' },
      { day: 4, title: 'Trở về Hà Nội', description: 'Kết thúc chuyến đi và trở về Hà Nội' },
    ],
    policies: [
      { title: 'Chính sách hủy tour', description: 'Hủy tour trước 7 ngày được hoàn 50% tiền cọc' },
      { title: 'Chính sách trẻ em', description: 'Trẻ em dưới 2 tuổi miễn phí, từ 2-10 tuổi tính 75% giá người lớn' },
    ],
    duration: '4N3Đ',
    starting_province_id: 'p1',
    destination_province_id: 'p2',
    transportation: 'Máy bay',
    representative_price: {
      adult: 7500000,
      new_price: 6800000,
    },
    departure_summary: [
      { departure_id: 'd3', departure_date: '2025-07-01' },
      { departure_id: 'd4', departure_date: '2025-07-25' },
    ],
    total_slots_booked: 2,
    is_bestseller: true,
    is_active: false,
  },
  {
    _id: 't8',
    tour_code: 'HN-DN-01',
    name: 'Hà Nội - Đà Nẵng 4 ngày 3 đêm',
    description: 'Tour du lịch Hà Nội - Đà Nẵng với nhiều điểm tham quan hấp dẫn',
    images: ['/placeholder.svg?height=200&width=300'],
    services: ['Ăn uống', 'Vé tham quan', 'Hướng dẫn viên', 'Vé máy bay'],
    itinerary: [
      { day: 1, title: 'Khởi hành từ Hà Nội', description: 'Khởi hành từ Hà Nội đi Đà Nẵng bằng máy bay' },
      { day: 2, title: 'Thăm quan Bà Nà Hills', description: 'Tham quan Bà Nà Hills và Cầu Vàng' },
      { day: 3, title: 'Thăm quan Hội An', description: 'Thăm quan phố cổ Hội An' },
      { day: 4, title: 'Trở về Hà Nội', description: 'Kết thúc chuyến đi và trở về Hà Nội' },
    ],
    policies: [
      { title: 'Chính sách hủy tour', description: 'Hủy tour trước 7 ngày được hoàn 50% tiền cọc' },
      { title: 'Chính sách trẻ em', description: 'Trẻ em dưới 2 tuổi miễn phí, từ 2-10 tuổi tính 75% giá người lớn' },
    ],
    duration: '4N3Đ',
    starting_province_id: 'p1',
    destination_province_id: 'p2',
    transportation: 'Máy bay',
    representative_price: {
      adult: 7500000,
      new_price: 6800000,
    },
    departure_summary: [
      { departure_id: 'd3', departure_date: '2025-07-01' },
      { departure_id: 'd4', departure_date: '2025-07-25' },
    ],
    total_slots_booked: 2,
    is_bestseller: false,
    is_active: false,
  },
  {
    _id: 't9',
    tour_code: 'HN-DN-01',
    name: 'Hà Nội - Đà Nẵng 4 ngày 3 đêm',
    description: 'Tour du lịch Hà Nội - Đà Nẵng với nhiều điểm tham quan hấp dẫn',
    images: ['/placeholder.svg?height=200&width=300'],
    services: ['Ăn uống', 'Vé tham quan', 'Hướng dẫn viên', 'Vé máy bay'],
    itinerary: [
      { day: 1, title: 'Khởi hành từ Hà Nội', description: 'Khởi hành từ Hà Nội đi Đà Nẵng bằng máy bay' },
      { day: 2, title: 'Thăm quan Bà Nà Hills', description: 'Tham quan Bà Nà Hills và Cầu Vàng' },
      { day: 3, title: 'Thăm quan Hội An', description: 'Thăm quan phố cổ Hội An' },
      { day: 4, title: 'Trở về Hà Nội', description: 'Kết thúc chuyến đi và trở về Hà Nội' },
    ],
    policies: [
      { title: 'Chính sách hủy tour', description: 'Hủy tour trước 7 ngày được hoàn 50% tiền cọc' },
      { title: 'Chính sách trẻ em', description: 'Trẻ em dưới 2 tuổi miễn phí, từ 2-10 tuổi tính 75% giá người lớn' },
    ],
    duration: '4N3Đ',
    starting_province_id: 'p1',
    destination_province_id: 'p2',
    transportation: 'Máy bay',
    representative_price: {
      adult: 7500000,
      new_price: 6800000,
    },
    departure_summary: [
      { departure_id: 'd3', departure_date: '2025-07-01' },
      { departure_id: 'd4', departure_date: '2025-07-25' },
    ],
    total_slots_booked: 2,
    is_bestseller: false,
    is_active: false,
  },
  {
    _id: 't10',
    tour_code: 'HCM-PQ-01',
    name: 'Hồ Chí Minh - Phú Quốc 5 ngày 4 đêm',
    description: 'Tour du lịch Hồ Chí Minh - Phú Quốc với nhiều điểm tham quan hấp dẫn',
    images: ['/placeholder.svg?height=200&width=300'],
    services: ['Ăn uống', 'Vé tham quan', 'Hướng dẫn viên', 'Vé máy bay'],
    itinerary: [
      { day: 1, title: 'Khởi hành từ Hồ Chí Minh', description: 'Khởi hành từ Hồ Chí Minh đi Phú Quốc bằng máy bay' },
      { day: 2, title: 'Thăm quan Nam Đảo', description: 'Tham quan các điểm du lịch ở Nam Đảo' },
      { day: 3, title: 'Tham quan Bắc Đảo', description: 'Tham quan các điểm du lịch ở Bắc Đảo' },
      { day: 4, title: 'Tham quan Vinpearl Safari', description: 'Tham quan Vinpearl Safari' },
      { day: 5, title: 'Trở về Hồ Chí Minh', description: 'Kết thúc chuyến đi và trở về Hồ Chí Minh' },
    ],
    policies: [
      { title: 'Chính sách hủy tour', description: 'Hủy tour trước 10 ngày được hoàn 70% tiền cọc' },
      { title: 'Chính sách trẻ em', description: 'Trẻ em dưới 2 tuổi miễn phí, từ 2-10 tuổi tính 60% giá người lớn' },
    ],
    duration: '5N4Đ',
    starting_province_id: 'p3',
    destination_province_id: 'p5',
    transportation: 'Máy bay',
    representative_price: {
      adult: 9500000,
      new_price: 8800000,
    },
    departure_summary: [
      { departure_id: 'd5', departure_date: '2025-08-25' },
      { departure_id: 'd6', departure_date: '2025-08-25' },
    ],
    total_slots_booked: 5,
    is_bestseller: true,
    is_active: true,
  },
  {
    _id: 't11',
    tour_code: 'HCM-PQ-01',
    name: 'Hồ Chí Minh - Phú Quốc 5 ngày 4 đêm',
    description: 'Tour du lịch Hồ Chí Minh - Phú Quốc với nhiều điểm tham quan hấp dẫn',
    images: ['/placeholder.svg?height=200&width=300'],
    services: ['Ăn uống', 'Vé tham quan', 'Hướng dẫn viên', 'Vé máy bay'],
    itinerary: [
      { day: 1, title: 'Khởi hành từ Hồ Chí Minh', description: 'Khởi hành từ Hồ Chí Minh đi Phú Quốc bằng máy bay' },
      { day: 2, title: 'Thăm quan Nam Đảo', description: 'Tham quan các điểm du lịch ở Nam Đảo' },
      { day: 3, title: 'Tham quan Bắc Đảo', description: 'Tham quan các điểm du lịch ở Bắc Đảo' },
      { day: 4, title: 'Tham quan Vinpearl Safari', description: 'Tham quan Vinpearl Safari' },
      { day: 5, title: 'Trở về Hồ Chí Minh', description: 'Kết thúc chuyến đi và trở về Hồ Chí Minh' },
    ],
    policies: [
      { title: 'Chính sách hủy tour', description: 'Hủy tour trước 10 ngày được hoàn 70% tiền cọc' },
      { title: 'Chính sách trẻ em', description: 'Trẻ em dưới 2 tuổi miễn phí, từ 2-10 tuổi tính 60% giá người lớn' },
    ],
    duration: '5N4Đ',
    starting_province_id: 'p3',
    destination_province_id: 'p5',
    transportation: 'Máy bay',
    representative_price: {
      adult: 9500000,
      new_price: 8800000,
    },
    departure_summary: [
      { departure_id: 'd5', departure_date: '2025-08-25' },
      { departure_id: 'd6', departure_date: '2025-08-25' },
    ],
    total_slots_booked: 5,
    is_bestseller: true,
    is_active: true,
  },
  {
    _id: 't12',
    tour_code: 'HCM-PQ-01',
    name: 'Hồ Chí Minh - Phú Quốc 5 ngày 4 đêm',
    description: 'Tour du lịch Hồ Chí Minh - Phú Quốc với nhiều điểm tham quan hấp dẫn',
    images: ['/placeholder.svg?height=200&width=300'],
    services: ['Ăn uống', 'Vé tham quan', 'Hướng dẫn viên', 'Vé máy bay'],
    itinerary: [
      { day: 1, title: 'Khởi hành từ Hồ Chí Minh', description: 'Khởi hành từ Hồ Chí Minh đi Phú Quốc bằng máy bay' },
      { day: 2, title: 'Thăm quan Nam Đảo', description: 'Tham quan các điểm du lịch ở Nam Đảo' },
      { day: 3, title: 'Tham quan Bắc Đảo', description: 'Tham quan các điểm du lịch ở Bắc Đảo' },
      { day: 4, title: 'Tham quan Vinpearl Safari', description: 'Tham quan Vinpearl Safari' },
      { day: 5, title: 'Trở về Hồ Chí Minh', description: 'Kết thúc chuyến đi và trở về Hồ Chí Minh' },
    ],
    policies: [
      { title: 'Chính sách hủy tour', description: 'Hủy tour trước 10 ngày được hoàn 70% tiền cọc' },
      { title: 'Chính sách trẻ em', description: 'Trẻ em dưới 2 tuổi miễn phí, từ 2-10 tuổi tính 60% giá người lớn' },
    ],
    duration: '5N4Đ',
    starting_province_id: 'p3',
    destination_province_id: 'p5',
    transportation: 'Máy bay',
    representative_price: {
      adult: 9500000,
      new_price: 8800000,
    },
    departure_summary: [
      { departure_id: 'd5', departure_date: '2025-08-25' },
      { departure_id: 'd6', departure_date: '2025-08-25' },
    ],
    total_slots_booked: 5,
    is_bestseller: true,
    is_active: true,
  },
  {
    _id: 't13',
    tour_code: 'HCM-PQ-01',
    name: 'Hồ Chí Minh - Phú Quốc 5 ngày 4 đêm',
    description: 'Tour du lịch Hồ Chí Minh - Phú Quốc với nhiều điểm tham quan hấp dẫn',
    images: ['/placeholder.svg?height=200&width=300'],
    services: ['Ăn uống', 'Vé tham quan', 'Hướng dẫn viên', 'Vé máy bay'],
    itinerary: [
      { day: 1, title: 'Khởi hành từ Hồ Chí Minh', description: 'Khởi hành từ Hồ Chí Minh đi Phú Quốc bằng máy bay' },
      { day: 2, title: 'Thăm quan Nam Đảo', description: 'Tham quan các điểm du lịch ở Nam Đảo' },
      { day: 3, title: 'Tham quan Bắc Đảo', description: 'Tham quan các điểm du lịch ở Bắc Đảo' },
      { day: 4, title: 'Tham quan Vinpearl Safari', description: 'Tham quan Vinpearl Safari' },
      { day: 5, title: 'Trở về Hồ Chí Minh', description: 'Kết thúc chuyến đi và trở về Hồ Chí Minh' },
    ],
    policies: [
      { title: 'Chính sách hủy tour', description: 'Hủy tour trước 10 ngày được hoàn 70% tiền cọc' },
      { title: 'Chính sách trẻ em', description: 'Trẻ em dưới 2 tuổi miễn phí, từ 2-10 tuổi tính 60% giá người lớn' },
    ],
    duration: '5N4Đ',
    starting_province_id: 'p3',
    destination_province_id: 'p5',
    transportation: 'Máy bay',
    representative_price: {
      adult: 9500000,
      new_price: 8800000,
    },
    departure_summary: [
      { departure_id: 'd5', departure_date: '2025-08-25' },
      { departure_id: 'd6', departure_date: '2025-08-25' },
    ],
    total_slots_booked: 5,
    is_bestseller: true,
    is_active: true,
  },
  {
    _id: 't14',
    tour_code: 'HCM-PQ-01',
    name: 'Hồ Chí Minh - Phú Quốc 5 ngày 4 đêm',
    description: 'Tour du lịch Hồ Chí Minh - Phú Quốc với nhiều điểm tham quan hấp dẫn',
    images: ['/placeholder.svg?height=200&width=300'],
    services: ['Ăn uống', 'Vé tham quan', 'Hướng dẫn viên', 'Vé máy bay'],
    itinerary: [
      { day: 1, title: 'Khởi hành từ Hồ Chí Minh', description: 'Khởi hành từ Hồ Chí Minh đi Phú Quốc bằng máy bay' },
      { day: 2, title: 'Thăm quan Nam Đảo', description: 'Tham quan các điểm du lịch ở Nam Đảo' },
      { day: 3, title: 'Tham quan Bắc Đảo', description: 'Tham quan các điểm du lịch ở Bắc Đảo' },
      { day: 4, title: 'Tham quan Vinpearl Safari', description: 'Tham quan Vinpearl Safari' },
      { day: 5, title: 'Trở về Hồ Chí Minh', description: 'Kết thúc chuyến đi và trở về Hồ Chí Minh' },
    ],
    policies: [
      { title: 'Chính sách hủy tour', description: 'Hủy tour trước 10 ngày được hoàn 70% tiền cọc' },
      { title: 'Chính sách trẻ em', description: 'Trẻ em dưới 2 tuổi miễn phí, từ 2-10 tuổi tính 60% giá người lớn' },
    ],
    duration: '5N4Đ',
    starting_province_id: 'p3',
    destination_province_id: 'p5',
    transportation: 'Máy bay',
    representative_price: {
      adult: 9500000,
      new_price: 8800000,
    },
    departure_summary: [
      { departure_id: 'd5', departure_date: '2025-08-25' },
      { departure_id: 'd6', departure_date: '2025-08-25' },
    ],
    total_slots_booked: 5,
    is_bestseller: true,
    is_active: true,
  },
];